/* A lexical scanner generated by ft_lex */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>

/* end standard C headers. */