/* A lexical scanner generated by ft_lex */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>

/* end standard C headers. */

void yy_fatal_error (const char* msg );
int yymore(void);
int yyless(int n);
int input(void);
int unput(int c);
int yywrap(void);
int yylex(void);
void yy_push_accepting_state(int state, int len_match);
void yy_init_buffer(void);
void yy_init_accepting_stack(void);
void yy_if_no_match(char *last_pos);
char *yy_next_char(void);
void yy_if_match();
