use crate::file_parsing::{
    definitions::{parse::list_all_states, Definition, DefinitionState},
    FilePart, YytextMode,
};

const LEXER_STRUCT: &str = include_str!("templates/lexer_struct.rs.tpl");
const LEXER_IMPL_METHODS: &str = include_str!("templates/lexer_impl_methods.rs.tpl");
const YYLEX_BODY: &str    = include_str!("templates/yylex_body.rs.tpl");

pub fn write_header_rust(
    definitions: &[Definition],
    _mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    writeln!(out, "// Generated by ft_lex")?;
    writeln!(out)?;
    writeln!(out, "const INITIAL: usize = 0;")?;
    for elem in definitions {
        match elem {
            Definition::ExclusiveState { name, state_nb } => {
                writeln!(out, "const {name}: usize = {state_nb};")?;
            }
            Definition::InclusiveState { name, state_nb } => {
                writeln!(out, "const {name}: usize = {state_nb};")?;
            }
            Definition::Bloc { content } | Definition::LineWithSpace { content } => {
                writeln!(out, "{content}")?;
            }
            _ => {}
        }
    }
    writeln!(out)
}

/// Emits the Lexer struct definition (module-level, before the tables).
pub fn write_yytext_section_rust(
    _mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    out.write_all(LEXER_STRUCT.as_bytes())
}

/// Emits the first `impl` block: fixed runtime methods + `yy_is_exclusive_state`.
/// The impl block is left OPEN for `write_action_rust` to add `yy_action`.
/// `write_accept_actions_rust` will close this impl block, emit module-level
/// accept statics, and reopen a second impl block for `write_yylex_rust`.
pub fn write_is_exclusive_state_rust(
    file_parts: &FilePart,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    // Emit the fixed runtime methods inside an impl block (left open).
    out.write_all(LEXER_IMPL_METHODS.as_bytes())?;
    writeln!(out)?;

    let all_states = list_all_states(file_parts.definitions());
    let exclusive: Vec<_> = all_states
        .iter()
        .filter(|(_, t)| *t == DefinitionState::Exclusive)
        .collect();

    writeln!(out, "    fn yy_is_exclusive_state(&self, state: usize) -> bool {{")?;
    if exclusive.is_empty() {
        writeln!(out, "        let _ = state;")?;
        writeln!(out, "        false")?;
    } else {
        writeln!(out, "        matches!(state,")?;
        let names: Vec<&str> = exclusive.iter().map(|(n, _)| n.as_str()).collect();
        writeln!(out, "            {}", names.join(" | "))?;
        writeln!(out, "        )")?;
    }
    writeln!(out, "    }}")?;
    writeln!(out)
}

pub fn write_action_rust(
    file_parts: &FilePart,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let action_hash = file_parts.map_actions();

    writeln!(out, "    fn yy_action(&mut self, action: usize) -> Option<i32> {{")?;
    writeln!(out, "        let state = self.yy_start;")?;

    // Check if any rule uses condition states, if not suppress unused variable warning
    let has_condition_states = file_parts
        .rule_action()
        .iter()
        .any(|r| !r.condition_state.is_empty());
    if !has_condition_states {
        writeln!(out, "        let _ = state;")?;
    }

    writeln!(out, "        match action {{")?;

    for nb_action in 1..=action_hash.len() {
        let action_str = get_key_by_value(action_hash, nb_action).unwrap();
        let condition_states = get_condition_states(file_parts, action_str);
        writeln!(out, "            {nb_action} => {{")?;
        if !condition_states.is_empty() {
            write_rust_condition_state_check(&condition_states, out)?;
        }
        if get_bol(file_parts, action_str) {
            writeln!(out, "                if !self.yy_at_bol {{ return None; }}")?;
        }
        if get_eol(file_parts, action_str) {
            writeln!(out, "                if !self.yy_at_eol() {{ return None; }}")?;
        }
        // Wrap user code: replace bare `return <expr>;` with `return Some(<expr>);`
        let wrapped = wrap_user_action(action_str);
        writeln!(out, "                {wrapped}")?;
        writeln!(out, "            }}")?;
    }
    writeln!(out, "            _ => {{}}")?;
    writeln!(out, "        }}")?;
    writeln!(out, "        None")?;
    writeln!(out, "    }}")?;
    writeln!(out)
}

/// Wraps a user action string for Rust emission.
///
/// - Replaces bare `yytext` with `self.yytext` so field access compiles.
/// - Replaces bare `return <expr>;` with `return Some(<expr> as i32);`.
/// Actions are otherwise emitted verbatim — users targeting `--rust` must
/// write Rust action code.
fn wrap_user_action(action: &str) -> String {
    let action = action.replace("yytext", "self.yytext");
    fix_return_stmts(&action)
}

fn fix_return_stmts(action: &str) -> String {
    let mut out = String::new();
    let mut remaining = action;
    while let Some(idx) = remaining.find("return ") {
        out.push_str(&remaining[..idx]);
        let after_return = &remaining[idx + 7..]; // skip "return "
        // Check if it's already `None` or `Some(`
        if after_return.starts_with("None") || after_return.starts_with("Some(") {
            out.push_str("return ");
            remaining = after_return;
        } else {
            // Find the semicolon to get the expression
            if let Some(semi_idx) = after_return.find(';') {
                let expr = after_return[..semi_idx].trim();
                if expr.is_empty() {
                    out.push_str("return None;");
                } else {
                    out.push_str(&format!("return Some({expr} as i32);"));
                }
                remaining = &after_return[semi_idx + 1..];
            } else {
                // No semicolon found, leave as-is
                out.push_str("return ");
                remaining = after_return;
            }
        }
    }
    out.push_str(remaining);
    out
}

fn get_key_by_value(map: &std::collections::HashMap<String, usize>, val: usize) -> Option<&String> {
    map.iter().find(|(_, &v)| v == val).map(|(k, _)| k)
}

fn get_condition_states(
    file_parts: &FilePart,
    action: &str,
) -> Vec<crate::file_parsing::definitions::ConditionState> {
    for elem in file_parts.rule_action() {
        if elem.action() == action {
            return elem.condition_state.clone();
        }
    }
    vec![]
}

fn get_bol(file_parts: &FilePart, action: &str) -> bool {
    file_parts.rule_action().iter().any(|r| r.action() == action && r.anchored_start)
}

fn get_eol(file_parts: &FilePart, action: &str) -> bool {
    file_parts.rule_action().iter().any(|r| r.action() == action && r.anchored_end)
}

fn write_rust_condition_state_check(
    states: &[crate::file_parsing::definitions::ConditionState],
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    if states.len() == 1 && states[0].name() == "INITIAL" {
        writeln!(out, "                if self.yy_is_exclusive_state(state) {{ return None; }}")?;
        return Ok(());
    }
    let conds: Vec<String> = states
        .iter()
        .map(|s| format!("state != {}", s.name()))
        .collect();
    writeln!(out, "                if {} {{ return None; }}", conds.join(" && "))?;
    Ok(())
}

pub fn write_yylex_rust(
    in_yylex: &[String],
    mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let mut in_yylex_content = String::new();
    for elem in in_yylex {
        in_yylex_content.push_str(elem);
    }
    let clear_yytext = match mode {
        YytextMode::Pointer | YytextMode::Array(_) => "self.yytext.clear(); self.yyleng = 0;",
    };
    let replaced = YYLEX_BODY
        .replace("#write_in_yylex", &in_yylex_content)
        .replace("change_me_clear_yytext!", clear_yytext);
    out.write_all(replaced.as_bytes())
}

pub fn write_user_routine_rust(
    user_routine: &str,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    // The user-routine section (after the second %%) is C code in a .l file.
    // Skip it entirely for Rust output; emitting C code would break compilation.
    let trimmed = user_routine.trim();
    if trimmed.is_empty() {
        return Ok(());
    }
    // Preserve the content as line comments so it is visible but inert.
    writeln!(out)?;
    writeln!(out, "// User routines (C only — not compiled by Rust backend):")?;
    for line in trimmed.lines() {
        writeln!(out, "// {line}")?;
    }
    Ok(())
}
