use crate::file_parsing::{
    definitions::{parse::list_all_states, Definition, DefinitionState},
    FilePart, YytextMode,
};
use std::fmt::Write;

const LEXER_STRUCT: &str = include_str!("templates/lexer_struct.rs.tpl");

pub fn write_header_rust(
    definitions: &[Definition],
    _mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    writeln!(out, "// Generated by ft_lex")?;
    writeln!(out, "#![allow(dead_code, unused_assignments)]")?;
    writeln!(
        out,
        "use ft_lex_runtime::{{ActionResult, LexerCore, LexerInterface, NxtTable, Tables, run_yylex}};"
    )?;
    writeln!(out)?;
    writeln!(out, "const INITIAL: usize = 0;")?;
    for elem in definitions {
        match elem {
            Definition::ExclusiveState { name, state_nb }
            | Definition::InclusiveState { name, state_nb } => {
                writeln!(out, "const {name}: usize = {state_nb};")?;
            }
            Definition::Bloc { content } | Definition::LineWithSpace { content } => {
                writeln!(out, "{content}")?;
            }
            _ => {}
        }
    }
    writeln!(out)
}

pub fn write_yytext_section_rust(
    _mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    out.write_all(LEXER_STRUCT.as_bytes())
}

pub fn write_is_exclusive_state_rust(
    file_parts: &FilePart,
    compressed: bool,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    writeln!(out, "impl<R: std::io::Read> LexerInterface for Lexer<R> {{")?;
    writeln!(out, "    type Reader = R;")?;
    writeln!(out)?;
    writeln!(
        out,
        "    fn get_core(&self) -> &LexerCore<R> {{ &self.core }}"
    )?;
    writeln!(
        out,
        "    fn get_core_mut(&mut self) -> &mut LexerCore<R> {{ &mut self.core }}"
    )?;
    writeln!(out)?;
    writeln!(out, "    fn tables(&self) -> Tables {{")?;
    writeln!(out, "        Tables {{")?;
    if compressed {
        writeln!(
            out,
            "            nxt: NxtTable::Packed {{ base: YY_BASE, nxt: YY_NXT_PACKED, chk: YY_CHK, def: YY_DEF }},"
        )?;
    } else {
        writeln!(
            out,
            "            nxt: NxtTable::Flat {{ cols: YY_NXT_COLS, flat: YY_NXT_FLAT }},"
        )?;
    }
    writeln!(out, "            yy_has_trans: YY_HAS_TRANS,")?;
    writeln!(out, "            yy_ec: YY_EC,")?;
    writeln!(out, "            yy_accept: YY_ACCEPT,")?;
    writeln!(out, "            yy_trailing: YY_TRAILING,")?;
    writeln!(out, "            yy_trailing_accept: YY_TRAILING_ACCEPT,")?;
    writeln!(out, "            yy_accept_cols: YY_ACCEPT_COLS,")?;
    writeln!(out, "            yy_accept_flat: YY_ACCEPT_FLAT,")?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out)?;

    let all_states = list_all_states(file_parts.definitions());
    let exclusive: Vec<_> = all_states
        .iter()
        .filter(|(_, t)| *t == DefinitionState::Exclusive)
        .collect();

    writeln!(
        out,
        "    fn yy_is_exclusive_state(&self, state: usize) -> bool {{"
    )?;
    if exclusive.is_empty() {
        writeln!(out, "        let _ = state;")?;
        writeln!(out, "        false")?;
    } else {
        writeln!(out, "        matches!(state,")?;
        let names: Vec<&str> = exclusive.iter().map(|(n, _)| n.as_str()).collect();
        writeln!(out, "            {}", names.join(" | "))?;
        writeln!(out, "        )")?;
    }
    writeln!(out, "    }}")?;
    writeln!(out)
}

pub fn write_action_rust(
    file_parts: &FilePart,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let action_hash = file_parts.map_actions();

    writeln!(
        out,
        "    fn yy_action(&mut self, action: usize) -> ActionResult {{"
    )?;
    writeln!(out, "        let state = self.yy_start;")?;

    let has_condition_states = file_parts
        .rule_action()
        .iter()
        .any(|r| !r.condition_state.is_empty());
    if !has_condition_states {
        writeln!(out, "        let _ = state;")?;
    }

    writeln!(out, "        match action {{")?;

    for nb_action in 1..=action_hash.len() {
        let action_str = get_key_by_value(action_hash, nb_action).unwrap();
        let condition_states = get_condition_states(file_parts, action_str);
        writeln!(out, "            {nb_action} => {{")?;
        if !condition_states.is_empty() {
            write_rust_condition_state_check(&condition_states, out)?;
        }
        if get_bol(file_parts, action_str) {
            writeln!(
                out,
                "                if !self.yy_at_bol {{ return ActionResult::GuardFailed; }}"
            )?;
        }
        if get_eol(file_parts, action_str) {
            writeln!(
                out,
                "                if !self.yy_at_eol() {{ return ActionResult::GuardFailed; }}"
            )?;
        }
        let wrapped = wrap_user_action(action_str);
        writeln!(out, "                {wrapped}")?;
        writeln!(out, "                return ActionResult::Continue;")?;
        writeln!(out, "            }}")?;
    }
    writeln!(out, "            _ => {{}}")?;
    writeln!(out, "        }}")?;
    writeln!(out, "        ActionResult::Continue")?;
    writeln!(out, "    }}")?;
    writeln!(out)
}

fn wrap_user_action(action: &str) -> String {
    let action = prepend_self_yytext(action);
    fix_return_stmts(&action)
}

fn prepend_self_yytext(action: &str) -> String {
    let mut result = String::new();
    let mut remaining = action;
    while let Some(idx) = remaining.find("yytext") {
        let prefix = &remaining[..idx];
        result.push_str(prefix);
        if prefix.ends_with("self.") {
            result.push_str("yytext");
        } else {
            result.push_str("self.yytext");
        }
        remaining = &remaining[idx + 6..];
    }
    result.push_str(remaining);
    result
}

fn fix_return_stmts(action: &str) -> String {
    let mut out = String::new();
    let mut remaining = action;
    while let Some(idx) = remaining.find("return ") {
        out.push_str(&remaining[..idx]);
        let after_return = &remaining[idx + 7..];
        if after_return.starts_with("ActionResult::") {
            out.push_str("return ");
            remaining = after_return;
        } else if let Some(semi_idx) = after_return.find(';') {
            let expr = after_return[..semi_idx].trim();
            if expr.is_empty() {
                out.push_str("return ActionResult::Continue;");
            } else {
                let _ = write!(out, "return ActionResult::Token({expr} as i32);");
            }
            remaining = &after_return[semi_idx + 1..];
        } else {
            out.push_str("return ");
            remaining = after_return;
        }
    }
    out.push_str(remaining);
    out
}

fn get_key_by_value(map: &std::collections::HashMap<String, usize>, val: usize) -> Option<&String> {
    map.iter().find(|(_, &v)| v == val).map(|(k, _)| k)
}

fn get_condition_states(
    file_parts: &FilePart,
    action: &str,
) -> Vec<crate::file_parsing::definitions::ConditionState> {
    for elem in file_parts.rule_action() {
        if elem.action() == action {
            return elem.condition_state.clone();
        }
    }
    vec![]
}

fn get_bol(file_parts: &FilePart, action: &str) -> bool {
    file_parts
        .rule_action()
        .iter()
        .any(|r| r.action() == action && r.anchored_start)
}

fn get_eol(file_parts: &FilePart, action: &str) -> bool {
    file_parts
        .rule_action()
        .iter()
        .any(|r| r.action() == action && r.anchored_end)
}

fn write_rust_condition_state_check(
    states: &[crate::file_parsing::definitions::ConditionState],
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    if states.len() == 1 && states[0].name() == "INITIAL" {
        writeln!(
            out,
            "                if self.yy_is_exclusive_state(state) {{ return ActionResult::GuardFailed; }}"
        )?;
        return Ok(());
    }
    let conds: Vec<String> = states
        .iter()
        .map(|s| format!("state != {}", s.name()))
        .collect();
    writeln!(
        out,
        "                if {} {{ return ActionResult::GuardFailed; }}",
        conds.join(" && ")
    )?;
    Ok(())
}

pub fn write_accept_actions_rust(
    file_parts: &FilePart,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let final_states = file_parts.actions();
    let action_map = file_parts.map_actions();
    let nb_states = file_parts.dfa().transitions().len();
    let max_actions = final_states
        .values()
        .map(std::vec::Vec::len)
        .max()
        .unwrap_or(0);
    let cols = max_actions + 1;
    let mut flat = vec![0usize; nb_states * cols];
    for (state, actions) in final_states {
        for (i, action_str) in actions.iter().rev().enumerate() {
            flat[state * cols + i] = *action_map.get(action_str).unwrap();
        }
    }

    writeln!(out, "}} // end impl LexerInterface for Lexer<R>")?;
    writeln!(out)?;
    writeln!(out, "const YY_ACCEPT_COLS: usize = {cols};")?;
    crate::lex_creation::rust::tables::write_usize_slice_pub("YY_ACCEPT_FLAT", &flat, out)?;
    writeln!(out)?;
    writeln!(out, "impl<R: std::io::Read> Lexer<R> {{")?;
    writeln!(out)
}

pub fn write_yylex_rust(
    in_yylex: &[String],
    _mode: YytextMode,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let mut in_yylex_content = String::new();
    for elem in in_yylex {
        in_yylex_content.push_str(elem);
    }

    writeln!(out, "    pub fn new(input: R) -> Self {{")?;
    writeln!(
        out,
        "        Lexer {{ core: ft_lex_runtime::LexerCore::new(input) }}"
    )?;
    writeln!(out, "    }}")?;
    writeln!(out)?;
    writeln!(out, "    pub fn begin(&mut self, state: usize) {{")?;
    writeln!(out, "        self.core.yy_start = state;")?;
    writeln!(out, "    }}")?;
    writeln!(out)?;
    writeln!(out, "    pub fn yylex(&mut self) -> i32 {{")?;
    if !in_yylex_content.trim().is_empty() {
        writeln!(out, "        {in_yylex_content}")?;
    }
    writeln!(out, "        run_yylex(self)")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}} // end impl<R: std::io::Read> Lexer<R>")?;
    writeln!(out)?;
    writeln!(out, "fn main() {{")?;
    writeln!(out, "    let mut lex = Lexer::new(std::io::stdin());")?;
    writeln!(out, "    lex.yylex();")?;
    writeln!(out, "}}")
}

pub fn write_user_routine_rust(
    user_routine: &str,
    out: &mut dyn std::io::Write,
) -> std::io::Result<()> {
    let trimmed = user_routine.trim();
    if trimmed.is_empty() {
        return Ok(());
    }
    writeln!(out)?;
    writeln!(
        out,
        "// User routines (C only — not compiled by Rust backend):"
    )?;
    for line in trimmed.lines() {
        writeln!(out, "// {line}")?;
    }
    Ok(())
}
