// Generated by ft_lex

#[derive(Clone, Copy)]
struct AcceptElem {
    action: usize,
    dfa_state: usize,
    len_match: usize,
}

pub struct Lexer<R: std::io::Read> {
    input: R,
    pub yytext: String,
    pub yyleng: usize,
    yy_start: usize,
    yy_init: bool,
    buffer: Vec<u8>,
    buffer_index: usize,
    stack: Vec<AcceptElem>,
    pub clean_flag: bool,
    pub yymore_flag: bool,
    pub yy_trailing_len: usize,
    pub yy_at_bol: bool,
}
